FROM ubuntu:18.04
MAINTAINER https://github.com/chineseocr/chineseocr
LABEL version="1.0"
EXPOSE 8080
EXPOSE 9999
RUN apt-get update
RUN apt-get install apt-utils vim libsm6 libxrender1 libxext-dev gcc g++ cmake poppler-utils libglib2.0-dev  -y
ENV DEBIAN_FRONTEND noninteractive
###下载Anaconda3 python 环境安装包 放置在chineseocr目录 url地址https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh
WORKDIR /chineseocr
ADD Miniconda3-latest-Linux-x86_64.sh /chineseocr
RUN cd /chineseocr && sh -c '/bin/echo -e "\nyes\n\nyes" | sh Miniconda3-latest-Linux-x86_64.sh'
#RUN echo -e "\ny" && /root/miniconda3/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
#RUN /root/miniconda3/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
#RUN /root/miniconda3/bin/conda config --set show_channel_urls yes
RUN echo -e "\ny" | /root/miniconda3/bin/conda install python=3.6
RUN /root/miniconda3/bin/pip install easydict h5py gevent requests -i https://pypi.tuna.tsinghua.edu.cn/simple/
RUN /root/miniconda3/bin/pip install bs4 matplotlib pillow keras==2.1.5 -U -i https://pypi.tuna.tsinghua.edu.cn/simple/
RUN /root/miniconda3/bin/pip install pdf2image python-docx -U -i https://pypi.tuna.tsinghua.edu.cn/simple/
RUN /root/miniconda3/bin/pip install web.py==0.40.dev0 regex redis flask gunicorn flask_restful -i https://pypi.tuna.tsinghua.edu.cn/simple/
ADD . /chineseocr
RUN cd /chineseocr/darknet && make clean && make && cd ..

RUN /root/miniconda3/bin/pip install /chineseocr/whl/Cython-0.29.21-cp36-cp36m-manylinux1_x86_64.whl -U
RUN /root/miniconda3/bin/pip install /chineseocr/whl/matplotlib-3.2.2-cp36-cp36m-manylinux1_x86_64.whl -U
RUN /root/miniconda3/bin/pip install /chineseocr/whl/lxml-4.5.1-cp36-cp36m-manylinux1_x86_64.whl -U
RUN /root/miniconda3/bin/pip install /chineseocr/whl/pandas-1.0.5-cp36-cp36m-manylinux1_x86_64.whl -U
RUN /root/miniconda3/bin/pip install /chineseocr/whl/tensorflow-1.9.0-cp36-cp36m-manylinux1_x86_64.whl -U
RUN /root/miniconda3/bin/pip install /chineseocr/whl/opencv_python-4.0.0.21-cp36-cp36m-manylinux1_x86_64.whl -U
RUN /root/miniconda3/bin/pip install /chineseocr/whl/opencv_contrib_python-4.0.0.21-cp36-cp36m-manylinux1_x86_64.whl -U
RUN /root/miniconda3/bin/pip install /chineseocr/whl/torch-1.5.1+cpu-cp36-cp36m-linux_x86_64.whl -U
RUN /root/miniconda3/bin/pip install /chineseocr/whl/torchvision-0.6.1+cpu-cp36-cp36m-linux_x86_64.whl -U
RUN rm -rf whl
RUN rm Miniconda3-latest-Linux-x86_64.sh
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
#ENTRYPOINT ["sh", "/chineseocr/start_ocr.sh"]
#RUN cd /chineseocr/text/detector/utils && sh make-for-cpu.sh
#RUN conda clean -p
#RUN conda clean -t
